  import type { Metadata } from "next";
  import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";
  import AppHeader from "@/src/components/layout/AppHeader";
  import SideBar from "@/src/components/layout/SideBar";
  import AppFooter from "@/src/components/layout/AppFooter";
  import LayoutClient from "@/src/components/layout/LayoutClient";

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body
          className="flex flex-col min-h-screen"
        >
          <AppHeader/>
          <div className="flex flex-1">
            <LayoutClient>
              {children}
            </LayoutClient>
          </div>
          <AppFooter/>

        </body>
      </html>
    );
  }
